version: "3.9"

services:

  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=choco
    ports:
      - "5499:5432"
    volumes:
      - ./mount/db:/var/lib/postgresql/data


