version: "3.9"

services:

  product_postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=product
    ports:
      - "5434:5432"
    volumes:
      - ./postgres_data/product/pgdata:/var/lib/postgresql/data


